# User config
author: "Tanya Lai"
tagline: "UMich CS"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Tanya, Tanya Lai, tanyalai"
email: "tanyalai@umich.edu"
linkedin: "https://www.linkedin.com/in/tanyalai23"
twitter: ""
github: "https://github.com/tanyalai"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
