# User config
author: "Tanya Lai"
tagline: "Undergraduate Computer Science Student @ University of Michigan, Ann Arbor"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "tanyalai@umich.edu"
linkedin: "https://www.linkedin.com/in/tanyalai23"
twitter: ""
github: "https://github.com/tanyalai"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
