# User config
author: "Tanya Lai"
tagline: "UMich CS"
description: "Tanya Lai's home page "
keywords: "Tanya, Tanya Lai, tanyalai"
email: "tanyalai@umich.edu"
linkedin: "https://www.linkedin.com/in/tanyalai23"
twitter: ""
github: "https://github.com/tanyalai"
spotify: "https://open.spotify.com/user/neogalactic54?si=W_GdU5OfTrOO34I1E8XqVA"
project: "projects"
res: "resumé"
ab: "about me"
course: "courses"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
