# User config
author: "Tanya Lai"
tagline: "UMich CS"
description: "I am a rising sophomore studying computer science and engineering at the University of Michigan, Ann Arbor. You can often catch me as the librarian and a double bassist for the "
keywords: "Tanya, Tanya Lai, tanyalai"
email: "tanyalai@umich.edu"
linkedin: "https://www.linkedin.com/in/tanyalai23"
twitter: ""
github: "https://github.com/tanyalai"
project: "projects"
res: "resumé"
ab: "about me"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
